version: "3.8"
services:
  store-db:
    image: supabase/postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_URL=${DIRECT_URL}
      # POSTGRES_USER: ${DB_USER}
      # POSTGRES_PASSWORD: ${DB_PASSWORD}
      # POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./postgres:/var/lib/postgresql/data
    # networks:
    #   - freecodecamp

  # pgadmin:
  #   image: dpage/pgadmin4:7.7
  #   container_name: pgadmin
  #   restart: always
  #   ports:
  #     - 5050:80
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: superman@google.com
  #     PGADMIN_DEFAULT_PASSWORD: superman
  #   depends_on:
  #     - dev-db

volumes:
  postgres:
    external: false
# networks:
#   freecodecamp:
